services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: edutrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/edutrack
      JWT_SECRET: "0d36cbd7231efdde5809df711e4ea4c5544d3ccd32bc8d43bb907fa0189cd3b8"
      SCHOOL_LAT: -6.771246975220776
      SCHOOL_LNG: 39.2405926971738
      SCHOOL_RADIUS_METERS: 2000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: pnpm exec tsx server.ts

volumes:
  pgdata:
